DROP DATABASE if exists NotesDB;
CREATE DATABASE NotesDB;

USE NotesDB;

DROP TABLE Note;

CREATE TABLE Note( 
    noteid SMALLINT NOT NULL AUTO_INCREMENT, 
    dateCreated DATE NOT NULL,
    contents VARCHAR(1000) NOT NULL,
    PRIMARY KEY (noteid)
);